/**
 * ============================================================================
 *  AETHERION — AUTONOMY & INTERNAL POLITICS  (the vassal rulebook)
 * ============================================================================
 *  The single source of truth for what a subordinate polity can and cannot do.
 *  sovereignty.json (generated by scripts/etl/build-sovereignty.mjs from Natural
 *  Earth) maps each dependency ADM0_A3 → its sovereign + an autonomy TIER; this
 *  file gives every tier its CONTROL MATRIX (develop / police / military /
 *  diplomacy) plus the tunables for the two independence paths and for province
 *  unrest → insurgency. Pure logic that reads this lives in sim/sovereignty.ts,
 *  sim/independence.ts and sim/unrest.ts. No hard-coded rules in components.
 */
import sovereigntyJson from './sovereignty.json';

/** INTEGRAL = a fully sovereign state (the default; not stored in the JSON). */
export type AutonomyTier =
  | 'INTEGRAL'
  | 'CONSTITUENT_COUNTRY'
  | 'FREE_ASSOCIATION'
  | 'OVERSEAS_TERRITORY'
  | 'MILITARY_LEASE';

/** What a polity of a given tier may do itself vs. what its sovereign handles. */
export interface Controls {
  develop: boolean; // build province development slots
  police: boolean; // internal security / counter-insurgency
  military: 'full' | 'militia' | 'none'; // raise armed forces
  diplomacy: 'full' | 'limited' | 'none'; // conduct its own foreign relations
  inheritsWars: boolean; // dragged into the sovereign's wars/alliances
}

export interface TierDef {
  label: string;
  short: string;
  blurb: string;
  controls: Controls;
  /** Baseline unrest pressure this tier adds (neglected territories simmer). */
  unrestBias: number; // 0..1
  /** How readily a peaceful referendum is granted (0 = never, 1 = trivially). */
  independenceEase: number; // 0..1
}

export const AUTONOMY: Record<AutonomyTier, TierDef> = {
  INTEGRAL: {
    label: 'Sovereign State',
    short: 'SOV',
    blurb: 'A fully independent state — full command of economy, forces and foreign policy.',
    controls: { develop: true, police: true, military: 'full', diplomacy: 'full', inheritsWars: false },
    unrestBias: 0,
    independenceEase: 0,
  },
  CONSTITUENT_COUNTRY: {
    label: 'Constituent Country',
    short: 'CON',
    blurb:
      'Home rule: your own economy, budget and police, and a local militia — but foreign affairs and war belong to the sovereign. A referendum for independence is realistic.',
    controls: { develop: true, police: true, military: 'militia', diplomacy: 'none', inheritsWars: true },
    unrestBias: 0.12,
    independenceEase: 0.7,
  },
  FREE_ASSOCIATION: {
    label: 'Associated State',
    short: 'ASC',
    blurb:
      'Near-sovereign in free association: you run your economy and limited local diplomacy; defence is delegated to your partner. Independence is largely a formality.',
    controls: { develop: true, police: true, military: 'militia', diplomacy: 'limited', inheritsWars: true },
    unrestBias: 0.06,
    independenceEase: 0.85,
  },
  OVERSEAS_TERRITORY: {
    label: 'Overseas Territory',
    short: 'OST',
    blurb:
      'Administered from afar: you may develop the land and keep a police force, but you raise no military and hold no foreign policy — those rest with the sovereign.',
    controls: { develop: true, police: true, military: 'none', diplomacy: 'none', inheritsWars: true },
    unrestBias: 0.2,
    independenceEase: 0.4,
  },
  MILITARY_LEASE: {
    label: 'Leased Territory',
    short: 'LSE',
    blurb: 'A leased enclave under the administering power. Development only; no forces, no diplomacy.',
    controls: { develop: true, police: true, military: 'none', diplomacy: 'none', inheritsWars: true },
    unrestBias: 0.1,
    independenceEase: 0.15,
  },
};

/** Typed view of the generated sovereignty map. */
export interface DependencyRec {
  sovereign: string;
  tier: AutonomyTier;
  kind: string;
  note?: string;
  contested?: boolean;
}

export const DEPENDENCIES: Record<string, DependencyRec> = sovereigntyJson.dependencies as Record<
  string,
  DependencyRec
>;
export const CONTESTED: ReadonlySet<string> = new Set(sovereigntyJson.contested as string[]);

/** Tunables for the two independence paths + province unrest. Tuned so war is
 *  rare and peaceful change is the norm (see the plan's war-avoidance goal). */
export const POLITICS = {
  independence: {
    /** Support (0..100) needed before a referendum can be called. */
    referendumThreshold: 60,
    /** Treasury cost (as a fraction of yearly revenue) to fund a campaign push. */
    campaignCostFrac: 0.04,
    /** Support gained per funded campaign push. */
    campaignPush: 12,
    /** Passive support drift per game-year from neglect (× tier unrestBias). */
    passiveDriftPerYear: 6,
    /** Referendum grant odds = base + support-weight×support01 + tierEase, minus
     *  a penalty for a hostile sovereign relationship. */
    grantBase: 0.1,
    grantSupportWeight: 0.5,
    grantEaseWeight: 0.4,
    hostilePenalty: 0.5,
  },
  unrest: {
    /** Unrest at/above this (0..100) tips a province into insurgency. Sits just
     *  above the peacetime ceiling of the worst-governed states, so eruptions
     *  are rare, organic, and concentrated where they'd really happen — war
     *  weariness (+22) makes conflict the great destabiliser. */
    insurgencyThreshold: 72,
    /** Unrest below this lets an active insurgency be brought back under control. */
    pacifyThreshold: 40,
    /** Underdevelopment pressure: (1 − devIndex) × this. Poor states simmer. */
    underdevWeight: 20,
    /** Tax strain weight — discounted by development (rich welfare states are
     *  taxed hard but consent; extraction without services breeds anger). */
    taxWeight: 18,
    warWearinessWeight: 22,
    /** Governance grievance by archetype (repression + weak legitimacy). */
    govUnrest: {
      Transitional: 14,
      Authoritarian: 9,
      'Hybrid Regime': 8,
      Theocracy: 8,
      'One-Party State': 6,
      'Absolute Monarchy': 5,
    } as Record<string, number>,
    /** Latent separatist identity: ~this share of provinces carry a hotspot
     *  bonus up to hotspotMax (deterministic per province — the ethnic/identity
     *  proxy until real culture data lands). */
    hotspotShare: 0.1,
    hotspotMax: 16,
    /** Built infrastructure calms a province (per tier, capped). */
    infraReliefPerTier: 1.2,
    infraReliefMax: 6,
    /** INVESTMENT HOPE — a construction project underway is a visible promise:
     *  relief starts at base the day ground breaks and ramps as it progresses
     *  (per project, all projects summed, capped). Cancelling forfeits it and
     *  adds cancelBacklash to the resentment ledger — broken promises cut
     *  deeper than none made. */
    investmentHopeBase: 4,
    investmentHopeRamp: 4,
    investmentHopeMax: 10,
    cancelBacklash: 8,
    /** DELIVERED development: each ECONOMIC tier the player completed
     *  (infrastructure/industry/port/special) keeps calming the province long
     *  after the ribbon-cutting — jobs, power, roads. Stacks with the passive
     *  infraRelief above but is much stronger: investment is the slow, durable
     *  answer to unrest that police surges are not. */
    devReliefPerTier: 2.0,
    devReliefMax: 12,
    /** Nationwide pressure from the fiscal state: IMF austerity bites welfare;
     *  a treasury running on fumes (reserves-financed deficit) breeds dread. */
    austerityUnrest: 7,
    fiscalCrisisUnrest: 8,
    /** Foreign-occupation flat unrest (a province held by a non-owner). */
    occupation: 45,
    /** Treasury cost per policing action (fraction of yearly revenue). */
    policeCostFrac: 0.02,
    /** Unrest removed per policing action. */
    policeRelief: 15,
    /** Unrest removed by granting a province a full autonomy step. */
    autonomyRelief: 30,
  },
  /** How long each internal-politics operation runs, in GAME-DAYS. Nothing the
   *  player orders lands instantly: ops are started, tracked, and resolved by
   *  politicsStore.tickPolitics. One operation per province at a time. */
  timing: {
    /** Police surge: relief ramps in linearly across the op, then decays. */
    policeDays: 30,
    /** Devolution: drafting and passing an autonomy statute. */
    devolveDays: 180,
    /** One counter-insurgency operation (growth pauses while forces engage). */
    suppressDays: 45,
    /** A funded independence campaign drips its support push over this window. */
    campaignDays: 90,
    /** An independence referendum is scheduled this far out when called. */
    referendumLeadDays: 60,
  },
  /** Bringing an autonomous region (granted autonomy, or an entrenched
   *  breakaway) back under full central control. Three roads:
   *
   *  REFERENDUM — cheap and clean, but consent is required: content provinces
   *  vote to return; entrenched de-facto states rarely do. Failure hardens them.
   *  POLITICAL — negotiated reincorporation: slow, expensive, guaranteed, and
   *  it leaves a residue of resentment among those who lost their privileges.
   *  FORCE — a crackdown campaign: fast and certain, but the region seethes for
   *  years and the WORLD watches — every nation's opinion of the aggressor falls.
   *  (Peaceful paths will instead affect nations that benefited from the old
   *  arrangement once trade lands — deferred hook, not modelled yet.) */
  reintegration: {
    /** Op durations (game-days). */
    referendumDays: 90,
    politicalDays: 240,
    forceDays: 120,
    /** Treasury cost per path (fraction of yearly revenue). */
    referendumCostFrac: 0.01,
    politicalCostFrac: 0.08,
    forceCostFrac: 0.05,
    /** Referendum odds = base + contentWeight × (1 − unrest/100), minus the
     *  entrenched penalty for de-facto states. Clamped 0.05..0.95. */
    oddsBase: 0.35,
    oddsContentWeight: 0.5,
    entrenchedPenalty: 0.3,
    /** Post-reintegration sentiment written into the resentment ledger:
     *  positive raises unrest, negative (goodwill) calms it. Decays toward 0. */
    referendumGoodwill: -15,
    politicalResentment: 12,
    forceResentment: 35,
    /** Resentment/goodwill decays toward 0 by this much per game-year. */
    resentmentDecayPerYear: 8,
    /** A failed referendum: separatist backlash + a long wait before retrying. */
    failBacklash: 10,
    retryCooldownDays: 360,
    /** Forced reintegration: flat opinion hit from every other nation. */
    aggressorWorldAnger: 18,
  },
  /** Standing down an operation mid-run: no refund (the money is spent), and
   *  some retreats read as betrayal — resentment added per op kind. Halting a
   *  police surge or a crackdown carries no grudge; walking back a promised
   *  autonomy statute or a negotiated return does. */
  cancel: {
    police: 0,
    devolve: 6,
    suppress: 0,
    reintegrate_referendum: 4,
    reintegrate_political: 6,
    reintegrate_force: 4,
  } as Record<string, number>,
} as const;

export const isDependencyTier = (t: AutonomyTier): boolean => t !== 'INTEGRAL';
